directories:
  dataset_dir: "../ADNI_train_dataset/"
  validation_dataset_dir: "../ADNI_validation_dataset/"
  results_dir: "./results_CFM_ADNI"
parameters:
  epochs: 1000
  batch_size: 4 # 8, 16 
  num_workers: 0
  input_size: 128
  num_channels: 64
  num_res_blocks: 2
  in_channels: 2  
  out_channels: 1  
  num_classes: 3  
  save_every: 1000
  lr: 2e-4
  loss_type: "le"
  warmup_steps: 5000
  lr_scheduler: "cos"
  lr_min: 2e-7
  gamma_decay: 0.9999
  pl_factor: 0.5
  pl_patience: 500
  update_ema_every: 10
  use_ema: True
  ema_decay: 0.995
  grad_norm: 1.0 
  val_seeds: [42, 135, 654]
wandb:
  key: 229d8cfea5ace41820f39a5df8d7fb7a3cdcca3d